version: 2
jobs:
  build:
    working_directory: ~/quiz-rt-social
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:8
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
  deploy:
    machine:
        enabled: true
    working_directory: ~/quiz-rt-social
    environment:
      HEROKU_APP: quizrtsocial
    steps:
      - run:
          name: Deploy Master to Heroku
          commands:
            - |
              cat >~/.netrc <<EOF
              machine api.heroku.com
                login $HEROKU_EMAIL
                password $HEROKU_TOKEN
              machine git.heroku.com
                login $HEROKU_EMAIL
                password $HEROKU_TOKEN
              EOF
            - chmod 600 ~/.netrc # Heroku cli complains about permissions without this
            - heroku container:login
            - heroku container:push web --app $HEROKU_APP
            - heroku container:release web
                timeout: 400 # if your deploys take a long time

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: dev-integration
      - test:
          requires:
            - build
          filters:
            branches:
              only: dev-integration
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dev-integration

        
