# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  machine:
    services:
      - docker

  dependencies:
    cache_directories:
      - ~/docker
  
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

  deployment:
    staging:
      commands:
        - docker login --username=_ --password=${HEROKU_APP_TOKEN} registry.heroku.com
        - docker build --rm=false -t registry.heroku.com/quiz-rt-social/web .
        - docker push registry.heroku.com/quiz-rt-social/web:latest
