version: 2
jobs:
  build:
    working_directory: ~/quiz-rt-social
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:4.8.2-jessie
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
  deploy:
    machine:
        enabled: true
    working_directory: ~/quiz-rt-social
    environment:
      HEROKU_APP: quizrtsocial
    steps:
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: feature-friends
      - test:
          requires:
            - build
          filters:
            branches:
              only: feature-friends
      - deploy:
          filters:
            branches:
              only: feature-friends 

        
